<a href="https://colab.research.google.com/github/AStevennino/ProgramacionAplicada/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
sample_list = [1,2,3]
np.array(sample_list)

array([1, 2, 3])

ARRAYS

In [ ]:
my_vector = np.array(['this','is','a','vector'])
print(my_vector)

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

['this' 'is' 'a' 'vector']


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.eye(1)
np.eye(2)
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# np.random.rand(sample_size)
# Returns a sample of random numbers between 0 and 1.
# Sample size can either be one integer (for a one-dimensional array) or two integers separated by commas (for a two-dimensional array).

np.random.rand(5)
np.random.rand(2,3)

array([[0.8778291 , 0.31127412, 0.10144517],
       [0.71261712, 0.46185697, 0.62284036]])

In [ ]:
# np.random.randn(sample_size)
# Returns a sample of random numbers between 0 and 1, following the normal distribution.
# Sample size can either be one integer (for a one-dimensional array) or two integers separated by commas (for a two-dimensional array).

np.random.randn(5)
np.random.randn(2,3)

array([[-1.19641038,  1.01626141, -0.15928907],
       [-1.02320523, -0.05018974,  0.2697785 ]])

In [ ]:
# np.random.randint(low, high, sample_size)
# Returns a sample of integers that are greater than or equal to 'low' and less than 'high'

np.random.randint(1, 10, 5)
#np.random.randint(0, 100, (3,2))

array([9, 2, 1, 6, 5])

In [ ]:
arr = np.array([0,1,2,3,4,5])
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr = np.array([0,1,2,3,4,5])
arr.shape

(6,)

In [ ]:
# arr = arr.reshape(2,3)
# arr.shape
arr.reshape(2,3).shape

(2, 3)

In [ ]:
simple_array = np.array([1,2,3,4])
simple_array.max()

np.int64(4)

In [ ]:
simple_array.argmax()

np.int64(3)

In [ ]:
simple_array.min()
simple_array.argmin()

np.int64(0)

METHODS AND OPERATIONS

In [ ]:
ar = np.arange(4)
ar

array([0, 1, 2, 3])

In [ ]:
2 + ar

array([2, 3, 4, 5])

In [ ]:
ar + ar

array([0, 2, 4, 6])

In [ ]:
ar - 10

array([-10,  -9,  -8,  -7])

In [ ]:
ar - ar

array([0, 0, 0, 0])

In [ ]:
6 * ar
# ar*ar

array([ 0,  6, 12, 18])

In [ ]:
arr / 2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5]])

In [ ]:
ar/ar

<ipython-input-71-10b1bc619fd4>:1: RuntimeWarning: invalid value encountered in divide
  ar/ar


array([nan,  1.,  1.,  1.])

In [ ]:
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [ ]:
np.exp(ar)
np.sin(ar)
np.cos(ar)
np.log(ar)

<ipython-input-75-f4ee8204d2b3>:4: RuntimeWarning: divide by zero encountered in log
  np.log(ar)


array([      -inf, 0.        , 0.69314718, 1.09861229])

INDEXING AND ASSIGNMENT

In [ ]:
arr = np.random.rand(5)
arr

array([0.94515925, 0.02818323, 0.30909592, 0.59033526, 0.94214051])

In [ ]:
arr = np.round(arr,2)
arr

array([0.95, 0.03, 0.31, 0.59, 0.94])

In [ ]:
arr[0]

np.float64(0.95)

In [ ]:
arr[:3]
arr[2:]
arr[1:4]

array([0.03, 0.31, 0.59])

assignment

In [ ]:
arr = np.array([0.12,0.94,0.66,0.73,0.83])
arr

array([0.12, 0.94, 0.66, 0.73, 0.83])

In [ ]:
arr[:] =0
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr[2:5] =0.5
arr

array([0. , 0. , 0.5, 0.5, 0.5])

referencing

In [ ]:
new_array = np.array([6, 7, 8, 9])

second_new_array = new_array[0:2]

second_new_array

array([6, 7])

In [ ]:
second_new_array[1] = 4

second_new_array

array([6, 4])

In [ ]:
new_array

array([6, 4, 8, 9])

In [ ]:
array_to_copy = np.array([1, 2, 3])
copied_array = array_to_copy.copy()
array_to_copy
copied_array

array([1, 2, 3])

In [ ]:
copied_array[0] = 9
copied_array
array_to_copy

array([1, 2, 3])

indexing two-dimensionl

In [ ]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
mat[1:][:2]

array([[20, 25, 30],
       [35, 40, 45]])

conditional

In [ ]:
arr = np.array([0.69, 0.94, 0.66, 0.73, 0.83])
arr>0.7

array([False,  True, False,  True,  True])

In [ ]:
arr[arr>0.7]

array([0.94, 0.73, 0.83])